"""verify-models-match-db

Revision ID: 1187dab72c43
Revises: 62122da5219e
Create Date: 2026-05-02 12:22:19.050176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1187dab72c43'
down_revision: Union[str, Sequence[str], None] = '62122da5219e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_call_history_details_campaign_processed', 'call_history_details', ['campaign_id', sa.literal_column('processed_at DESC')], unique=False)
    op.create_index('ix_call_history_details_opportunity_processed', 'call_history_details', ['opportunity_id', sa.literal_column('processed_at DESC')], unique=False)
    op.create_index('ix_call_history_details_room_id', 'call_history_details', ['room_id'], unique=False, postgresql_where=sa.text('room_id IS NOT NULL'))
    op.create_index('ix_rooms_start_timestamp', 'rooms', ['start_timestamp'], unique=False, postgresql_where=sa.text('start_timestamp IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rooms_start_timestamp', table_name='rooms', postgresql_where=sa.text('start_timestamp IS NOT NULL'))
    op.drop_index('ix_call_history_details_room_id', table_name='call_history_details', postgresql_where=sa.text('room_id IS NOT NULL'))
    op.drop_index('ix_call_history_details_opportunity_processed', table_name='call_history_details')
    op.drop_index('ix_call_history_details_campaign_processed', table_name='call_history_details')
    # ### end Alembic commands ###
