"""verify-models-match-db

Revision ID: 1187dab72c43
Revises: 62122da5219e
Create Date: 2026-05-02 12:22:19.050176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1187dab72c43'
down_revision: Union[str, Sequence[str], None] = '62122da5219e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adversary',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('mode', sa.Enum('ADVERSARY', 'CHAT', name='adversarymode'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'STOPPED', name='adversarystatus'), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_call_history_details_campaign_processed', 'call_history_details', ['campaign_id', sa.literal_column('processed_at DESC')], unique=False)
    op.create_index('ix_call_history_details_opportunity_processed', 'call_history_details', ['opportunity_id', sa.literal_column('processed_at DESC')], unique=False)
    op.create_index('ix_call_history_details_room_id', 'call_history_details', ['room_id'], unique=False, postgresql_where=sa.text('room_id IS NOT NULL'))
    op.create_index('ix_rooms_start_timestamp', 'rooms', ['start_timestamp'], unique=False, postgresql_where=sa.text('start_timestamp IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rooms_start_timestamp', table_name='rooms', postgresql_where=sa.text('start_timestamp IS NOT NULL'))
    op.drop_index('ix_call_history_details_room_id', table_name='call_history_details', postgresql_where=sa.text('room_id IS NOT NULL'))
    op.drop_index('ix_call_history_details_opportunity_processed', table_name='call_history_details')
    op.drop_index('ix_call_history_details_campaign_processed', table_name='call_history_details')
    op.drop_table('adversary')
    # ### end Alembic commands ###
