"""set room fields as nullable

Revision ID: 420f69b8becc
Revises: 54a59a9ca3f3
Create Date: 2026-03-20 00:58:26.077336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420f69b8becc'
down_revision: Union[str, Sequence[str], None] = '54a59a9ca3f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'thread_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('rooms', 'opportunity_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'opportunity_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('rooms', 'thread_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
