"""Add substage and rating columns

Revision ID: 4c1942062646
Revises: 8907dc215cb6
Create Date: 2026-03-26 13:53:14.442567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c1942062646'
down_revision: Union[str, Sequence[str], None] = '8907dc215cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_details', sa.Column('substage', sa.String(), nullable=True))
    op.add_column('campaign_details', sa.Column('rating', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_details', 'rating')
    op.drop_column('campaign_details', 'substage')
    # ### end Alembic commands ###
