"""add cancelled_at in campaigns

Revision ID: 5a4d2c0b5e3f
Revises: 188bf1ff8072
Create Date: 2026-04-13 19:41:04.475494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a4d2c0b5e3f'
down_revision: Union[str, Sequence[str], None] = '188bf1ff8072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_scheduled_events_dispatch', 'scheduled_events', ['scheduled_at'], unique=False, postgresql_where=sa.text("status IN ('pending', 'dispatching')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduled_events_dispatch', table_name='scheduled_events', postgresql_where=sa.text("status IN ('pending', 'dispatching')"))
    op.drop_column('campaigns', 'cancelled_at')
    # ### end Alembic commands ###
