"""add campaign capabilities

Revision ID: 62122da5219e
Revises: 624c95f4acf2
Create Date: 2026-04-20 08:45:27.135261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import echo.db.models.campaign


# revision identifiers, used by Alembic.
revision: str = '62122da5219e'
down_revision: Union[str, Sequence[str], None] = '624c95f4acf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('capabilities', echo.db.models.campaign.CapabilitiesType(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'capabilities')
    # ### end Alembic commands ###
