"""add_last_called_at_to_campaign_detail

Revision ID: 8f477b1aaa38
Revises: f331c26a50c0
Create Date: 2026-05-16 20:52:06.088949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f477b1aaa38'
down_revision: Union[str, Sequence[str], None] = 'f331c26a50c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_details', sa.Column('last_called_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_details', 'last_called_at')
    # ### end Alembic commands ###
