"""baseline

Revision ID: bd6a64f4d0b6
Revises:
Create Date: 2026-02-23 23:05:59.898375

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "bd6a64f4d0b6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
