"""Modified analytics table and campaign detail

Revision ID: c9bcddac826f
Revises: a7b7cd263de1
Create Date: 2026-03-07 11:16:42.425365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9bcddac826f'
down_revision: Union[str, Sequence[str], None] = 'a7b7cd263de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_history_details_bk')
    op.add_column('call_history_details', sa.Column('plancode', sa.Text(), nullable=True))
    op.add_column('call_history_details', sa.Column('market', sa.Text(), nullable=True))
    op.alter_column('call_history_details', 'opportunity_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('campaign_details', sa.Column('market', sa.String(), nullable=False))
    op.add_column('campaign_details', sa.Column('plancode', sa.String(), nullable=False))
    op.create_index('ix_campaign_status', 'campaign_details', ['campaign_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_campaign_status', table_name='campaign_details')
    op.drop_column('campaign_details', 'plancode')
    op.drop_column('campaign_details', 'market')
    op.alter_column('call_history_details', 'opportunity_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('call_history_details', 'market')
    op.drop_column('call_history_details', 'plancode')
    op.create_table('call_history_details_bk',
    sa.Column('room_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('opportunity_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('voicemail_answer', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('availability', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recording_consent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('motivation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('work_status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('financial_interest', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('financial_topics', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('financial_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('objection', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('callback_requested', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('callback_reference_day', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('callback_day', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('callback_time', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recording_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('insight_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('insight_id', name=op.f('call_history_details_bk_pkey'))
    )
    # ### end Alembic commands ###
