"""create campaign model

Revision ID: cabbd272ea70
Revises: ac9e4cf7ea31
Create Date: 2026-02-24 22:44:51.030546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cabbd272ea70'
down_revision: Union[str, Sequence[str], None] = 'ac9e4cf7ea31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'PAUSED', 'CANCELLED', name='campaignstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('completed_users', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RETRY', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'DO_NOT_CALL', name='campaignuserstatus'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_called_at', sa.DateTime(), nullable=True),
    sa.Column('next_call_after', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['users.opportunity_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'opportunity_id', name='uq_campaign_opportunity')
    )
    op.create_index('ix_campaign_status', 'campaign_details', ['campaign_id', 'status'], unique=False)
    op.create_index('ix_next_call_after', 'campaign_details', ['next_call_after'], unique=False)
    op.alter_column('call_history_details', 'opportunity_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'opportunity_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'opportunity_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('call_history_details', 'opportunity_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index('ix_next_call_after', table_name='campaign_details')
    op.drop_index('ix_campaign_status', table_name='campaign_details')
    op.drop_table('campaign_details')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
