"""movidas del lucas que no sabe hacer el

Revision ID: cac2d8139a63
Revises: 4c1942062646
Create Date: 2026-04-07 15:12:23.424218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac2d8139a63'
down_revision: Union[str, Sequence[str], None] = '4c1942062646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_call_history_campaign_id', 'call_history_details', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_call_history_campaign_id', table_name='call_history_details')
    # ### end Alembic commands ###
