"""Modified campaign details

Revision ID: d8fa1030cd62
Revises: 21384d79932d
Create Date: 2026-03-04 19:51:40.096074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8fa1030cd62'
down_revision: Union[str, Sequence[str], None] = '21384d79932d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_details', sa.Column('attempts', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.drop_index(op.f('ix_next_call_after'), table_name='campaign_details')
    op.drop_column('campaign_details', 'next_call_after')
    op.drop_column('campaign_details', 'last_called_at')
    op.drop_column('campaign_details', 'attempt_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_details', sa.Column('attempt_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('campaign_details', sa.Column('last_called_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('campaign_details', sa.Column('next_call_after', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_next_call_after'), 'campaign_details', ['next_call_after'], unique=False)
    op.drop_column('campaign_details', 'attempts')
    # ### end Alembic commands ###
