import os

# SIP Trunk
SIP_TRUNK_ID = os.environ["SIP_TRUNK_ID"]
SIP_NUMBER = os.environ["SIP_NUMBER"]

# Azure
AZURE_ACCOUNT_NAME = os.environ["AZURE_ACCOUNT_NAME"]
AZURE_ACCOUNT_KEY = os.environ["AZURE_ACCOUNT_KEY"]
AZURE_CONTAINER = os.environ["AZURE_CONTAINER"]

# SendGrid
SENDGRID_AUTH_TOKEN = os.getenv("SENDGRID_AUTH_TOKEN")
SENDGRID_MAIL_FROM = os.getenv("SENDGRID_MAIL_FROM")
SENDGRID_MAIL_TO = os.getenv("SENDGRID_MAIL_TO")

# OpenAI
OPENAI_API_KEY = os.environ["OPENAI_API_KEY"]
OPENAI_MODEL_MINI = os.environ["OPENAI_MODEL_MINI"]

# Livekit
LIVEKIT_URL = os.environ["LIVEKIT_URL"]
LIVEKIT_API_KEY = os.environ["LIVEKIT_API_KEY"]
LIVEKIT_API_SECRET = os.environ["LIVEKIT_API_SECRET"]
