"""Add opportunity_id index to room table

Revision ID: 188bf1ff8072
Revises: cac2d8139a63
Create Date: 2026-04-08 12:20:41.900474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '188bf1ff8072'
down_revision: Union[str, Sequence[str], None] = 'cac2d8139a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_rooms_opportunity_id'), 'rooms', ['opportunity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_opportunity_id'), table_name='rooms')
    # ### end Alembic commands ###
