"""add_quality_and_program_fields_to_call_history

Revision ID: 1910088251c9
Revises: c9bcddac826f
Create Date: 2026-03-10 17:47:37.482173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1910088251c9'
down_revision: Union[str, Sequence[str], None] = 'c9bcddac826f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_history_details', sa.Column('quality_notes', sa.Text(), nullable=True))
    op.add_column('call_history_details', sa.Column('user_satisfaction', sa.Text(), nullable=True))
    op.add_column('call_history_details', sa.Column('frustration', sa.Boolean(), nullable=True))
    op.add_column('call_history_details', sa.Column('hallucination_detected', sa.Boolean(), nullable=True))
    op.add_column('call_history_details', sa.Column('compliance_risk_detected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_history_details', 'compliance_risk_detected')
    op.drop_column('call_history_details', 'hallucination_detected')
    op.drop_column('call_history_details', 'frustration')
    op.drop_column('call_history_details', 'user_satisfaction')
    op.drop_column('call_history_details', 'quality_notes')
    # ### end Alembic commands ###
