"""add agent name to campaigns

Revision ID: 21384d79932d
Revises: e29d3e3cd320
Create Date: 2026-03-01 18:40:39.948807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21384d79932d'
down_revision: Union[str, Sequence[str], None] = 'e29d3e3cd320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('agent_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'agent_name')
    # ### end Alembic commands ###
