"""add error col in jobs

Revision ID: 624c95f4acf2
Revises: 610e4a7b0d73
Create Date: 2026-04-19 08:21:45.364138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '624c95f4acf2'
down_revision: Union[str, Sequence[str], None] = '610e4a7b0d73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'error')
    # ### end Alembic commands ###
