"""add scheduled_at to campaigns

Revision ID: b9299f88fb73
Revises: 766bbb6ac2cf
Create Date: 2026-02-26 10:56:01.774949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9299f88fb73'
down_revision: Union[str, Sequence[str], None] = '766bbb6ac2cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'scheduled_at')
    # ### end Alembic commands ###
