"""add payment_methods and matgo_link to campaign_details

Revision ID: cd0478f30a03
Revises: 8f477b1aaa38
Create Date: 2026-05-25 19:58:11.993478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd0478f30a03'
down_revision: Union[str, Sequence[str], None] = '8f477b1aaa38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_details', sa.Column('payment_methods', sa.String(), nullable=True))
    op.add_column('campaign_details', sa.Column('matgo_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_details', 'matgo_link')
    op.drop_column('campaign_details', 'payment_methods')
    # ### end Alembic commands ###
