"""add excluded status

Revision ID: f331c26a50c0
Revises: 1187dab72c43
Create Date: 2026-05-13 16:53:04.585125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f331c26a50c0'
down_revision: Union[str, Sequence[str], None] = '1187dab72c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE campaignuserstatus ADD VALUE IF NOT EXISTS 'EXCLUDED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
